### ISSUE TITLE
Header / Footer

### ISSUE THREAD

**Issue by ianrohde** [iFixit/nextjs-community#1]
There's a fair amount of logic in the existing header. We should look into capabilities for loading a stand-alone Next.js app like this in a blank template with the header and footer. How? I don't know yet... 🙃 

Not sure if this is on the roadmap already, but it has come up multiple times and would be an accelerator for new projects.

**Comment by djmetzle** [comment]
@bhuminson mentioned at standup this morning that we need to think about the Login modal as well here.

I would posit it might be optimal for us to be able to publish these components in a generic way. Perhaps with a private NPM package? 

Another good reuse strategy would be something like [module federation](https://webpack.js.org/concepts/module-federation/)? We are a monorepo shop afterall! :sweat_smile:

**Comment by bhuminson** [comment]
Yup, the header will be converted to a more standalone version here https://github.com/iFixit/ifixit/issues/39258 by @andyg0808, and I believe a standalone footer has already been implemented by inkOfPixel and the integration of it will be handled here https://github.com/iFixit/ifixit/issues/39162

**Comment by probablyian** [comment]
Sounds like this is being handled 👍
